### ISSUE TITLE
Release chef 16 compatible cookbook

### ISSUE THREAD

**Issue by asvinours** [petracvv/logstash_lwrp#7]
Hello,

We worked together on a new version of this cookbook to make it compatible with Chef 16 a few weeks ago.
Any chance you could release it soon?

I see some builds are failing on CircleCI but I can't check what exactly is failing.

I'm sure you have a lot of things to deal with and this cookbook is probably not your priority. Do you think maybe you could contact the sous-chef community to transfer ownership of this repo to them?

thank you,

**Comment by petracvv** [comment]
I finally got around to doing this today. Version 2.0.0 is available on supermarket now. I'll look into the sous-chefs transfer as I simply haven't had much time to do Chef work since I started doing more Ansible in the past few months.
